/* 
 * Deliveree API
 *
 * With Deliveree API, developers can integrate our on-demand local delivery platform into their applications. The API is designed for developers to check prices, book an immediate or scheduled delivery and follow updates until delivery completion.
 *
 * 
 * Contact: duke@deliveree.com
 * Generated by: https://deliveree.com
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace IO.Deliveree.Model
{
    /// <summary>
    /// Quote
    /// </summary>
    [DataContract]
    public partial class Quote : IEquatable<Quote>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Quote" /> class.
        /// </summary>
        /// <param name="pickupTime"></param>
        /// <param name="vehicleTypeId"></param>
        /// <param name="packs"></param>
        /// <param name="timeType">Only accept now or schedule.</param>
        /// <param name="locations">locations.</param>
        public Quote(DateTime? pickupTime = default(DateTime?),
                    int? vehicleTypeId = default(int?),
                    List<Pack> packs = default(List<Pack>),
                    string timeType = default(string),
                    List<Location> locations = default(List<Location>))
        {
            TimeType = timeType;
            Locations = locations;
            PickupTime = pickupTime;
            VehicleTypeId = vehicleTypeId;
            Packs = packs;
        }

        /// <summary>
        /// Only accept now or schedule
        /// </summary>
        /// <value>Only accept now or schedule</value>
        [DataMember(Name = "time_type", EmitDefaultValue = false)]
        public string TimeType { get; set; }
        /// <summary>
        /// Gets or Sets pickup_time
        /// </summary>
        [DataMember(Name = "pickup_time", EmitDefaultValue = false)]
        public DateTime? PickupTime { get; set; }
        /// <summary>
        /// Gets or Sets vehicle_type_id
        /// </summary>
        [DataMember(Name = "vehicle_type_id", EmitDefaultValue = false)]
        public int? VehicleTypeId { get; set; }
        /// <summary>
        /// Gets or Sets packs
        /// </summary>
        [DataMember(Name = "packs", EmitDefaultValue = false)]
        public List<Pack> Packs { get; set; }
        /// <summary>
        /// Gets or Sets Locations
        /// </summary>
        [DataMember(Name = "locations", EmitDefaultValue = false)]
        public List<Location> Locations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Quote {\n");
            sb.Append("  PickupTime: ").Append(PickupTime).Append("\n");
            sb.Append("  VehicleTypeId: ").Append(VehicleTypeId).Append("\n");
            sb.Append("  Packs: ").Append(Packs).Append("\n");
            sb.Append("  TimeType: ").Append(TimeType).Append("\n");
            sb.Append("  Locations: ").Append(Locations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Quote);
        }

        /// <summary>
        /// Returns true if Quote instances are equal
        /// </summary>
        /// <param name="input">Instance of Quote to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Quote input)
        {
            if (input == null)
                return false;

            return
                (
                    this.TimeType == input.TimeType ||
                    (this.TimeType != null &&
                    this.TimeType.Equals(input.TimeType))
                ) &&
                (
                    this.Locations == input.Locations ||
                    this.Locations != null &&
                    input.Locations != null &&
                    this.Locations.SequenceEqual(input.Locations)
                ) &&
                (
                    this.PickupTime == input.PickupTime ||
                    (this.PickupTime != null &&
                    this.TimeType.Equals(input.PickupTime))
                ) &&
                (
                    this.VehicleTypeId == input.VehicleTypeId ||
                    (this.VehicleTypeId != null &&
                    this.VehicleTypeId.Equals(input.VehicleTypeId))
                ) &&
                (
                    this.Packs == input.Packs ||
                    this.Packs != null &&
                    input.Packs != null &&
                    this.Packs.SequenceEqual(input.Packs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TimeType != null)
                    hashCode = hashCode * 59 + this.TimeType.GetHashCode();
                if (this.Locations != null)
                    hashCode = hashCode * 59 + this.Locations.GetHashCode();
                if (this.Packs != null)
                    hashCode = hashCode * 59 + this.Packs.GetHashCode();
                if (this.PickupTime != null)
                    hashCode = hashCode * 59 + this.PickupTime.GetHashCode();
                if (this.VehicleTypeId != null)
                    hashCode = hashCode * 59 + this.VehicleTypeId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
